catch (const char *msg)
    {
        cout << "ERROR !! Division by zero" << '\n';
    }